name: "colmena build"
on:
  push:
  schedule:
  - cron: "36 13 * * 6"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix develop --command colmena build
    - run: >
        nix develop --command nix path-info -Sh "$(nix develop --command colmena eval --instantiate -E '{ nodes, ... }: nodes.desktop2k.config.system.build.toplevel')"
