hello: ENC[AES256_GCM,data:TMwukG323Tx4BOsaulRBQnmlWUgzbeFBuu6caMnBK0BGHvfEp32F7ZMs6vNk/g==,iv:EVZwORdRWw6Oa4B7aXsfJDufpCUeIWgS3+gWSd1BLOQ=,tag:nQqnif5kFSJzopK+yu0ftQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kvlx3yuhnvheyqhskm7svxj7dtxrlhn5zykw0mds7zxzyrg46v8qsl0zg6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByVFZZT2dKRzB1S3JFU0F4
            UDBSd0ltb0tTUE05SVdnbHY3M3ZpbFVpS21RClBmVnJrbDQ1TkVMdkdaV2dPT0s2
            bGxtbzJqcC9TeC9ZeDFJaENqNlNEVU0KLS0tIHhzMk1yd3dLWDAxWXJnYzhKclFw
            ZlYzcHNrUWxnT09NbmxpZWc0aERzdEkKkOfpcXYJp9DKWSJ9u8rnmDb8eBqFco+g
            zBS19mFoVNgNl9Mcs+UeuqnY5/xZF9DhSFOcjv/942zWIiRAhSnFuw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1s5su283lxe3kadl7y3nxepwejq6gvyr4t2v08fmxr7mg56au55gqdtpxuh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1UkswYTFJSmQvZFBWeXJN
            OXdoOEt2bFlsMGFxOFJXZndQWStXZEtFRkU0Cnk2b3czV2QraDdTSnJ6Q3lKdkh3
            cVpKd3k5TjZiUURqVFBNb0paVU0vODQKLS0tIFV5bWRtblBjbzMxTFhtVkp0VWVk
            KzMxTmh5emtISXdkOUxSbGZFcEpwMUEKdiAOCf8FGJT3B8OGBR25OtdBCsD8YqL7
            D/15CuUOa7dV2sTI/Hra6hsn2bYpQLc0gxWeI/I3emvO+ftAtZqvEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-28T16:47:48Z"
    mac: ENC[AES256_GCM,data:3UxNmIiCZmIgQlThyGCu9bLApVi5vcRQFZVPExbhpnXg2YEmzQk2C/c+BbCeucD7lFECMGs1N0dlJvjh+/1i/QRFfZU/tSL3W2K1WI/j3JM3xEiwzAdaCGXl+tCj2wNA+BGTd6moV12nLR9eKyv2nbh9TiMb+mv2VS1kRG5f6mI=,iv:d7ESkqvXaHnYgZxwHAUL+Fjc0ZeDKsQxAze43l+HydA=,tag:IM6C+e3dNNJTm/hRxy9eOA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
